"""Add rating system

Revision ID: 225ccb75f41c
Revises: 
Create Date: 2025-03-29 21:16:26.933177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225ccb75f41c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('average_rating')

    # ### end Alembic commands ###
